:PROPERTIES:
:ID:       affine-variety
:END:
#+title: Affine Variety
#+date: [2020-12-14 Mon]
#+hugo_lastmod: [2026-02-17 Tue 12:19]
#+bibliography: ref.bib
#+cite_export: csl
#+hugo_tags: math

#+BEGIN_def
<<.def-nb>> *[[.def-nb][Definition nb]]*. Let \(\mathbb{F}\) be a [[file:field.org::.def-8][field]] and \(n\) a positive
integer. The \(n\)-dimensional *affine space* over \(\mathbb{F}\) is the set
\[\mathbb{F}^n = \{(a_1, \ldots, a_n) \mid a_1, \ldots, a_n \in \mathbb{F}\}.\]
#+END_def

#+BEGIN_rem
<<.rem-nn>> *[[.rem-nn][Remark nn]]*. A [[file:polynomial.org::.def-bh][polynomial]]
\(f \in \mathbb{F}[x_1, \ldots, x_n]\) can be regarded as a function
\(f : \mathbb{F}^n \to \mathbb{F}\) that takes points in the [[.def-nb][affine space]]
\(\mathbb{F}^n\) and produces elements of the [[file:field.org::.def-8][field]] \(\mathbb{F}\). A *zero
point* or *root* of \(f\) is a point
\(\mathbf{a} = (a_1, \ldots, a_n) \in \mathbb{F}^n\) such that
\(f(\mathbf{a}) = 0\).
#+END_rem

#+BEGIN_def
<<.def-nd>> *[[.def-nd][Definition nd]]*. Let
\(\{f_1, \ldots, f_s\} \subset \mathbb{F}[x_1, \ldots, x_n]\) be a set of
[[file:polynomial.org::.def-bh][polynomials]] and \(\mathbb{F}^n\) an [[.def-nb][affine space]]. The *affine variety*
\(V(f_1, \ldots, f_s)\) defined by \(\{f_1, \ldots, f_s\}\) is the set
\[V(f_1, \ldots, f_s) = \{(a_1, \ldots, a_n) \in \mathbb{F}^n \mid f_i(a_1, \ldots, a_n) = 0 \text{ for all } 1 \le i \le s\}\]
of all common [[.rem-nn][zero points]] of the polynomials in
\(\{f_1, \ldots, f_s\}\).
#+END_def

Solving an equation that can be expressed as a [[file:polynomial.org::.def-bh][polynomial]] in
multiple variables can be seen as finding the [[.rem-nn][zero points]] of the
corresponding polynomial. [[.def-nd][Affine varieties]] generalize this notion to
systems of polynomial equations.

#+BEGIN_ex
<<.exp-dq>> *[[.exp-dq][Example dq]]*. Consider the real coordinate space
\(\mathbb{R}^2\) and the [[file:polynomial.org::.def-bh][polynomial]]
\(f(x, y) = x^2 + y^2 - 1\). The [[.def-nd][variety]] \(V(f)\) is the unit
circle centered at the origin.
#+END_ex

#+BEGIN_pr
<<.prp-nr>> *[[.prp-nr][Proposition nr]]*. If \(\{f_1, \ldots, f_s\}\) and
\(\{g_1, \ldots, g_t\}\) are two [[file:ideal.org::.def-bs][bases]] of the same [[file:ideal.org::.def-m][ideal]] in
\(\mathbb{F}[x_1, \ldots, x_n]\), so that
\(\langle f_1, \ldots, f_s \rangle = \langle g_1, \ldots, g_t \rangle\), then
\(V(f_1, \ldots, f_s) = V(g_1, \ldots, g_t)\).

/Proof./ Choose any
\((a_1, \ldots, a_n) \in V(f_1, \ldots, f_s)\). All [[file:polynomial.org::.def-bh][polynomials]] in
\(\{f_1, \ldots, f_s\}\) are zero at \((a_1, \ldots, a_n)\). Now choose any
\(g \in \langle g_1, \ldots, g_t \rangle\). Since
\(\langle g_1, \ldots, g_t \rangle = \langle f_1, \ldots, f_s \rangle\), we can
write \(g = \sum_{i=1}^s h_i f_i\),
\(h_i \in \mathbb{F}[x_1, \ldots, x_n]\). Then
\(g(a_1, \ldots, a_n) = \sum_{i=1}^s h_i(a_1, \ldots, a_n) \cdot f_i(a_1, \ldots, a_n) = 0\),
which shows that
\(V(f_1, \ldots, f_s) \subseteq V(g_1, \ldots, g_t)\). The opposite inclusion
follows by the same argument.
#+END_pr

[[file:ideal.org::.exp-dp][Example dp]] shows that an [[file:ideal.org::.def-m][ideal]] may have multiple different
[[file:ideal.org::.def-bs][bases]] while [[.prp-nr][Proposition nr]] reveals that a [[.def-nd][variety]] is
determined by the ideal generated by its basis and not by the basis itself.

#+BEGIN_def
<<.def-dx>> *[[.def-dx][Definition dx]]*. Let
\(I \subseteq \mathbb{F}[x_1, \ldots, x_n]\) be an [[file:ideal.org::.def-m][ideal]]. We denote by
\(V(I)\) the set
\[V(I) = \{(a_1, \ldots, a_n) \in \mathbb{F}^n \mid f(a_1, \ldots, a_n) = 0 \text{ for all } f \in I\}.\]
#+END_def

#+BEGIN_pr
<<.prp-do>> *[[.prp-do][Proposition do]]*. \(V(I)\) is an [[.def-nd][affine variety]]. In
particular, if \(I = \langle f_1, \ldots, f_m \rangle\), then
\(V(I) = V(f_1, \ldots, f_m)\) [cite:@iva].
#+END_pr

In combination with the Hilbert Basis Theorem
([[file:groebner-basis.org::.thm-n4][Theorem n4]]), [[.prp-do][Proposition do]]
shows that even though a nonzero [[file:ideal.org::.def-m][ideal]] contains infinitely many
[[file:polynomial.org::.def-bh][polynomials]], its [[.def-nd][variety]] can still be defined by a finite set of
polynomial equations. [[.prp-do][Proposition do]] is a generalization of
[[.prp-nr][Proposition nr]].

#+BEGIN_def
<<.def-nf>> *[[.def-nf][Definition nf]]*. Let \(V \subseteq \mathbb{F}^n\) be an
[[.def-nd][affine variety]]. The *ideal of* \(V\) is defined as
\[I(V) = \{f \in \mathbb{F}[x_1, \ldots, x_n] \mid f(a_1, \ldots, a_n) = 0 \text{ for all } (a_1, \ldots, a_n) \in V\}.\]
#+END_def

#+BEGIN_pr
<<.prp-ng>> *[[.prp-ng][Proposition ng]]*. If \(V \subseteq \mathbb{F}^n\) is an
[[.def-nd][affine variety]], then \(I(V) \subseteq \mathbb{F}[x_1, \ldots, x_n]\) is an
[[file:ideal.org::.def-m][ideal]].

/Proof./ We have \(0 \in I(V)\) since the zero [[file:polynomial.org::.def-bh][polynomial]] vanishes on
all points in \(\mathbb{F}^n\). Now let \(f, g \in I(V)\),
\(h \in \mathbb{F}[x_1, \ldots, x_n]\), and let \((a_1, \ldots, a_n)\) be an
arbitrary point in \(V\). We get
\(f(a_1, \ldots, a_n) + g(a_1, \ldots, a_n) = 0 + 0 = 0\) and
\(h(a_1, \ldots, a_n) \cdot f(a_1, \ldots, a_n) = h(a_1, \ldots, a_n) \cdot 0 = 0\),
which shows that \(I(V)\) is an [[file:ideal.org::.def-m][ideal]].
#+END_pr

#+print_bibliography:
