:PROPERTIES:
:ID:       ideal
:END:
#+title: Ideal
#+date: [2020-03-04 Wed]
#+hugo_lastmod: [2023-12-01 Fri 22:08]
#+bibliography: ref.bib
#+cite_export: csl
#+hugo_tags: math

#+BEGIN_df
<<.def-m>> *[[.def-m][Definition m]]*. Let \(R\) be a commutative [[file:ring.org::.def-g][ring]] and \(\emptyset \ne I \subseteq R\). Then
\(I\) is an *ideal* of \(R\) if:
1. The sum \(a + b\) is in \(I\) for all \(a, b \in I\).
2. The product \(ar\) is in \(I\) for all \(a \in I\) and \(r \in R\).
The ideal \(I\) is *proper* if \(I \ne R\).
#+END_df

#+BEGIN_rem
<<.rem-c>> *[[.rem-c][Remark c]]*. [[.def-m][Definition m]] says that if \(R\) is a commutative [[file:ring.org::.def-g][ring]],
and \(\emptyset \neq I \subseteq R\), then \(I\) is an [[.def-m][ideal]] of \(R\) if:
1. The set \(I\) is closed under addition.
2. The set \(I\) is closed under multiplication by any \(r \in R\).
#+END_rem

#+BEGIN_pr
<<.prp-p>> *[[.prp-p][Proposition p]]*. Let \(I\) be an [[.def-m][ideal]] of a commutative [[file:ring.org::.def-g][ring]] \(R\).
Then:
1. The equation \(a \cdot 0 = 0 \cdot a = 0\) holds for all \(a \in R\).
2. The element \(0\) is in \(I\).
3. If \(1 \in I\) then \(I\) is not proper.

/Proof./ (i) Suppose \(a \in R\). Then
\(a + a \cdot 0 = a \cdot 1 + a \cdot 0 = a(1 + 0) = a \cdot 1 = a\). Adding
the additive inverse of \(a\) on both sides gives \(a \cdot 0 = 0\). Since \(R\)
is commutative, \(0 \cdot a = 0\) also holds. (ii) By the ring axioms,
\(0 \in R\), and by the [[.def-m][ideal]] definition, \(0 \cdot a = 0 \in I\)
for any \(a \in I\). (iii) Since \(1\) is the multiplicative identity,
\(1 \cdot r = r \in I\) for all \(r \in R\), and thus \(I = R\).
#+END_pr

#+BEGIN_rem
<<.rem-dm>> *[[.rem-dm][Remark dm]]*. There is an analogy from modular arithmetic that
illustrates an intuitive view of [[.def-m][ideals]]. Consider the [[file:ring.org::.def-g][ring]]
\(\mathbb{Z}_n\) of integers modulo \(n \in \mathbb{Z}\). The exact set of
integers that we identify with \(0\) in \(\mathbb{Z}_n\) is the set
\(n\mathbb{Z} = \{nm \mid m \in \mathbb{Z}\}\). This set meets the criteria for
being an ideal of \(\mathbb{Z}\) and its elements behave like \(0\) in
\(\mathbb{Z}\): adding two elements of \(n\mathbb{Z}\) yields another element of
\(n\mathbb{Z}\) and multiplying any element of \(n\mathbb{Z}\) again yields an
element of \(n\mathbb{Z}\).
#+END_rem

Considering our definition of [[file:ring.org::.def-g][rings]], an [[.def-m][ideal]] might not be a
ring itself. For example, consider the ring of integers and its ideal consisting
of even numbers. This ideal is not a ring since it has no multiplicative
identity.

#+BEGIN_def
<<.def-bw>> *[[.def-bw][Definition bw]]*. Let \(I\) be an [[.def-m][ideal]] of a [[file:ring.org::.def-g][ring]] \(R\). The
*coset* of \(I\) defined by \(a \in R\) is the set \(\{b + a \mid b \in I\}\),
denoted \(I + a\) or \([a]\).
#+END_def

#+BEGIN_rem
<<.rem-bi>> *[[.rem-bi][Remark bi]]*. The addition of cosets is defined by
\((I + a) + (I + a') = I + (a + a')\) and multiplication by
\((I + a)(I + a') = I + aa'\). The set of all [[.def-bw][cosets]] forms a [[file:ring.org::.def-g][ring]]
under these operations [cite:@shoup]. This ring is denoted \(R / I\) and called
the *quotient ring*.
#+END_rem

#+BEGIN_def
<<.def-bs>> *[[.def-bs][Definition bs]]*. Let
\(\{f_1, \ldots, f_s\} \subset \mathbb{F}[\mathbf{x}]\) be a set of
[[file:polynomial.org::.def-bh][polynomials]]. Then
\[\langle f_1, \ldots, f_s \rangle = \left\{\sum_{i=1}^s h_i f_i \mid h_1, \ldots, h_s \in \mathbb{F}[\mathbf{x}]\right\}.\]
The set \(\langle f_1, \ldots, f_s \rangle\) is an [[.def-m][ideal]] of
\(\mathbb{F}[\mathbf{x}]\) called the *ideal generated by*
\(\{f_1, \ldots, f_s\}\). The set \(\{f_1, \ldots, f_s\}\) is a *basis* of
\(\langle f_1, \ldots, f_s \rangle\).

/Proof./ Assume \(f = \sum_{i=1}^s p_i f_i\) and \(g = \sum_{i=1}^s q_i f_i\)
are [[file:polynomial.org::.def-bh][polynomials]], and let \(h \in \mathbb{F}[\mathbf{x}]\). Then
\[f + g = \sum_{i=1}^s (p_i + q_i) f_i \quad \text{and} \quad hf = \sum_{i=1}^s (hp_i) f_i\]
show that \(\langle f_1, \ldots, f_s \rangle\) meets the criteria for being an
[[.def-m][ideal]] of \(\mathbb{F}[\mathbf{x}]\).
#+END_def

[[.rem-dm][Remark dm]] provides an intuitive view of ideals through modular
arithmetic. Another analogy comes from linear algebra where the definition of
subspaces can be likened to the definition of ideals of
[[file:polynomial.org::.rem-b9][polynomial rings]]. Both are closed under
addition. Subspaces are closed under multiplication by scalars while ideals of
polynomial rings are closed under multiplication by polynomials.

#+BEGIN_pr
<<.prp-dc>> *[[.prp-dc][Proposition dc]]*. Let
\(I \subseteq \mathbb{F}[\mathbf{x}]\) be an [[.def-m][ideal]], and let
\(\{f_1, \ldots, f_s\} \subset \mathbb{F}[\mathbf{x}]\) be a set of
[[file:polynomial.org::.def-bh][polynomials]]. Then \(\langle f_1, \ldots, f_s \rangle \subseteq I\) if and
only if \(\{f_1, \ldots, f_s\} \subseteq I\).

/Proof./ (\(\implies\)) Assume
\(\langle f_1, \ldots, f_s \rangle \subseteq I\). Each \(f_i\) can be
constructed as \(f_i = 0 \cdot f_1 + \cdots + 1 \cdot f_i + \cdots + 0 \cdot f_s\),
and hence \(\{f_1, \ldots, f_s\} \subseteq I\). (\(\impliedby\)) Assume
\(\{f_1, \ldots, f_s\} \subseteq I\) and choose any
\(f \in \langle f_1, \ldots, f_s \rangle\) so that
\(f = h_1 f_1 + \cdots + h_s f_s\) where each
\(h_i \in \mathbb{F}[\mathbf{x}]\). We see that \(f \in I\) since \(I\) is an
[[.def-m][ideal]] and so
\(\langle f_1, \ldots, f_s \rangle \subseteq I\).
#+END_pr

#+BEGIN_ex
<<.exp-dp>> *[[.exp-dp][Example dp]]*. Consider the [[.def-m][ideals]]
\(\langle x, y \rangle\) and \(\langle x + y, x - y \rangle\) in the
[[file:polynomial.org::.rem-b9][polynomial ring]]
\(\mathbb{Q}[x, y]\). We will show that
\(\langle x, y \rangle = \langle x + y, x - y \rangle\). We see that
\(x + y \in \langle x, y \rangle\) and \(x - y \in \langle x, y \rangle\), so
by [[.prp-dc][Proposition dc]],
\(\langle x + y, x - y \rangle \subseteq \langle x, y \rangle\). Similarly,
both \(x = \frac{1}{2}(x + y) + \frac{1}{2}(x - y)\) and
\(y = \frac{1}{2}(x + y) - \frac{1}{2}(x - y)\) are in
\(\langle x + y, x - y \rangle\), so by [[.prp-dc][Proposition dc]],
\(\langle x, y \rangle \subseteq \langle x + y, x - y \rangle\) and the
equality follows.
#+END_ex

#+print_bibliography:
