:PROPERTIES:
:ID:       ring
:END:
#+title: Ring
#+date: [2020-01-30 Thu]
#+hugo_lastmod: [2023-08-06 Sun 21:18]
#+bibliography: ref.bib
#+cite_export: csl
#+hugo_tags: math

#+BEGIN_def
<<.def-g>> *[[.def-g][Definition g]]*. A *ring* is a set $R$ with two [[file:group.org::.def-d][binary operations]]
$\left( a, b \right) \mapsto a + b$ and $\left( a, b \right) \mapsto a \cdot b$, referred to as
addition and multiplication, such that the following axioms hold:
1. The set $R$ is an Abelian [[file:group.org::.def-e][group]] under addition with the *additive identity*
   $0$.
2. The set $R$ is a [[file:group.org::.def-r][monoid]] under multiplication with the *multiplicative
   identity* $1$.
3. Distributivity: Equations $a \cdot \left( b + c \right) = a \cdot b + a \cdot c$ and
   $\left( a + b \right) \cdot c = a \cdot c + b \cdot c$ hold for all $a, b, c \in R$.
A ring is a *commutative ring* if it is a commutative [[file:group.org::.def-r][monoid]] under
multiplication.
#+END_def

#+BEGIN_re
<<.rem-e>> *[[.rem-e][Remark e]]*.
1. The inverse under addition in a [[.def-g][ring]] is the *additive inverse*, and the
   inverse under multiplication is the *multiplicative inverse*.
2. We usually omit the symbol for multiplication, and instead of $a \cdot b$, we
   write $ab$.
3. We can think of subtraction in a [[.def-g][ring]] as addition of the additive inverse.
4. We can't think of division as multiplication by the multiplicative inverse
   since not every element has it's multiplicative inverse.
6. Axiom 3. describes the left and right distributive laws.
#+END_re

#+BEGIN_ex
<<.exp-j>> *[[.exp-j][Example j]]*.
1. The sets $\mathbb{Z}$, $\mathbb{Q}$, $\mathbb{R}$, and $\mathbb{C}$ are [[.def-g][rings]] with their standard
   addition and multiplication.
2. The natural numbers do not form a [[.def-g][ring]] since not all elements have their
   additive inverse in this set.
3. The set of integers modulo $n \in \mathbb{Z}$, denoted $\mathbb{Z}_n$, is a [[.def-g][ring]].
#+END_ex

Since we will not encounter any rings that are not commutative, we adopt the
convention that by a [[.def-g][ring]], we will mean a commutative ring. The only
difference between [[.def-g][rings]] and [[file:field.org::.def-8][fields]] is that in a field,
every element other than \(0\) has its multiplicative inverse. Note that every
[[file:field.org::.def-8][field]] is a ring as well.
